Repository wecode-bootcamp-korea/25-1st-SPAOGAME-backend, pull requests merged in 2021-10, with the labels that each got.

#2 ADD: postings/models.py , products/models.py, orders/models.py 수정
  core/models.py
  orders/models.py
  orders/urls.py
  postings/models.py
  postings/urls.py
  products/models.py
  products/urls.py
  spao/settings.py
  spao/urls.py
  users/models.py
  users/urls.py
Labels: Status: 리뷰 요청

#7 [송영록] ADD : 로그인 구현
  users/apps.py
  users/urls.py
  users/views.py
Labels: Status: Conflict 해결 요청

#9 [송영록] UPDATE : 데이터베이스 모델링 수정, orders/models.py 테이블변경
  orders/migrations/0001_initial.py
  orders/migrations/0002_initial.py
  orders/migrations/0003_alter_basket_product.py
  orders/migrations/0004_auto_20211012_1050.py
  orders/migrations/0005_auto_20211012_1204.py
  orders/models.py
  orders/views.py
  postings/apps.py
  postings/migrations/0001_initial.py
  postings/migrations/0002_initial.py
  postings/models.py
  products/migrations/0001_initial.py
  products/migrations/0002_rename_thumbnail_product_thumbnail_image_url.py
  products/models.py
  users/migrations/0001_initial.py
  users/models.py
  users/views.py
Labels: Status: 도움 요청, Status: 리뷰 요청

#8 [김주현] Add : postings앱 제품후기 등록 기능구현
  postings/models.py
  postings/urls.py
  postings/views.py
Labels: Status: 수정 요청, Status: Conflict 해결 요청
